vndk: Add android.hardware.power-V3-ndk to VndkMustUseVendorVariantList
SM8475 and SM8550 uses the AIDL V3 PowerHal

This Fixes the following error:
media/klozz/T-Force/out/soong/.intermediates/hardware/interfaces/power/aidl/android.hardware.power-V3-ndk/android_vendor.33_arm64_armv8-2a-dotprod_kryo385_shared/android.hardware.power-V3-ndk.so ) && (touch /run
/media/klozz/T-Force/out/target/product/lisa/obj/SHARED_LIBRARIES/android.hardware.power-V3-ndk.vendor_intermediates/same_vndk_variants.timestamp )"
ERROR: VNDK library android.hardware.power-V3-ndk has different core and vendor variants! This means that the copy used in the system.img/etc and vendor.img/etc images are different. In order to preserve space o
n some devices, it is helpful if they are the same. Frequently,  libraries are different because they or their dependencies compile things based on the macro '__ANDROID_VNDK__' or they specify custom options und
er 'target: { vendor: { ... } }'. Here are some possible resolutions:
ERROR: 1). Remove differences, possibly using the libvndksupport function android_is_in_vendor_process in order to turn this into a runtime difference.
ERROR: 2). Add the library to the VndkMustUseVendorVariantList variable in build/soong/cc/config/vndk.go, which is used to acknowledge this difference.

(vendor)libraries are different because they are differen from core version

Change-Id: I7cf0137e21d29aa88939f21f5b465a69fdcc763a
Signed-off-by: klozz <carlosj@klozz.dev>